Only set stream mapping for streams that provide 'codec_type'
Some containers allow streams that do not provide a 'codec_type' (Eg. TS). These files will cause the plugin to throw an exception that is not handled:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 272, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/video_remuxer/plugin.py", line 262, in on_worker_process

    mapper.streams_need_processing()

  File "/config/.unmanic/plugins/video_remuxer/lib/ffmpeg/stream_mapper.py", line 319, in streams_need_processing

    return self.__set_stream_mapping()

  File "/config/.unmanic/plugins/video_remuxer/lib/ffmpeg/stream_mapper.py", line 183, in __set_stream_mapping

    if stream_info.get('codec_type').lower() == "video":

AttributeError: 'NoneType' object has no attribute 'lower'
```